name: Deloy website
on: [push]
jobs:
  build:
    runs-on: ubuntu-lastest
    name: Deploy to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and deploy to surge domain
        uses: action/setup-node/@v1
        with:
          node-version: 8
      - run: npm install --global surge
      - run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}