name: Deloy website
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Code/Ex4_LayOutNewShop/
    name: Deploy to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and deploy to surge domain
        uses: actions/setup-node/@v1
        with:
          node-version: 8
      - run: npm install --global surge
      - run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
  react:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Code/my-app/
    name: deploy react
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and deploy to surge domain
        uses: actions/setup-node/@v1
        with:
          node-version: 8
      - run: npm install --global surge
      - run: surge ./ ${{ secrets.SURGE_DOMAIN_REACT }} --token ${{ secrets.SURGE_TOKEN }}
